name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vitax-production
          path: dist/
